--CREATE PROCEDURE PARA AUTOMATIZAR INSERCION
CREATE OR REPLACE PROCEDURE CREAR_SERVICIOS (NUM_DIAS IN INTEGER, NUM_MES IN INTEGER, ANIO IN INTEGER) IS
BEGIN
    FOR i in 1..NUM_DIAS
    LOOP
        INSERT INTO SERVICIOS
        SELECT SEQ_ID_SERVICIOS.nextval, i||'/'||NUM_MES||'/'||ANIO, 0, ' ', 'LIBRE', M.ID_MESA, T.ID_TURNO 
            FROM TURNOS T, MESAS M;
    END LOOP;
END;