ALTER SESSION SET "_ORACLE_SCRIPT" = true;

CREATE USER ISO2 IDENTIFIED BY ISO2
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;
    
GRANT DBA TO ISO2;
GRANT CONNECT, RESOURCE TO ISO2;

COMMIT;