/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Empleado;
import Dominio.GestorCamarero;
import Dominio.GestorServicio;
import Dominio.Servicio;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author pikac
 */
public class IU_Asignar_Camarero extends javax.swing.JFrame {

    private final WindowListener exitListener;
    private IU_Gestion_Reservas formGestion;
    private ModeloTabla modelo;
    
    /**
     * Creates new form IU_Asignar_Camarero
     */
    public IU_Asignar_Camarero() {
        this.exitListener = new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                formGestion.setVisible(true);
                cerrar();
            }
        };
        
        //Establecemos el modelo de tabla
        modelo = new ModeloTabla();
        
        initComponents();
        
        this.setTitle("ASIGNAR CAMARERO");
        this.setLocationRelativeTo(null); 
        this.addWindowListener(exitListener);
        
        //Ajustes de la tabla
        tableCamareros.getTableHeader().setReorderingAllowed(false);
        cargarTabla(); cargarDatos(); 
    }
    
    private void cargarTabla() {
        String nombreColumnas [] = {"ID_CAMARERO", "DNI", "NOMBRE", "APELLIDOS", "TELEFONO"};
        
        for (String nombreColumna : nombreColumnas) {
            modelo.addColumn(nombreColumna);
        }
        
        TableColumn id = tableCamareros.getColumn("ID_CAMARERO");
        id.setMinWidth(80);
        
        TableColumn dni = tableCamareros.getColumn("DNI");
        dni.setMinWidth(80);
        
        TableColumn nombre = tableCamareros.getColumn("NOMBRE");
        nombre.setMinWidth(80);
        
        TableColumn apellidos = tableCamareros.getColumn("APELLIDOS");
        apellidos.setMinWidth(80);
        
        TableColumn tfno = tableCamareros.getColumn("TELEFONO");
        tfno.setMinWidth(80);
    }
    
    public void cargarDatos() {
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        
        ArrayList<Empleado> lista = GestorCamarero.buscarListaCamareros(IU_Gestion_Reservas.sesionEmpleado.getnRestaurante());
        
        Object[] obj = new Object[5];
        for (int i = 0; i < lista.size(); i++) {
            Empleado e = lista.get(i);
            
            obj[0] = String.valueOf(e.getIdEmpleado());
            obj[1] = e.getDNI();
            obj[2] = e.getNombre();
            obj[3] = e.getApellidos();
            obj[4] = e.getTfno_contacto();
            
            modelo.addRow(obj);
        }
    }
    
    public void cargarServicio() {
        Servicio s = GestorServicio.buscarDatosServicio(Integer.parseInt(txtIdServicio.getText()));
        txtComentarios.setText(s.getComentarios());
        if (s.getNum_comensales() == 0) {
            cboNumComensales.setSelectedIndex(0);
        } else {
            cboNumComensales.setSelectedItem(String.valueOf(s.getNum_comensales()));
        }
    }

    private void cerrar() {
        this.dispose();
    }
    
    public void setFormGestionReservas (IU_Gestion_Reservas formGestion) {
        this.formGestion = formGestion;
    }
    
    public void setDatosServicio (String idServicio, String turno, String mesa, String fecha) {
        txtIdServicio.setText(idServicio);
        txtTurno.setText(turno);
        txtMesa.setText(mesa);
        txtFecha.setText(fecha);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReservaMesas = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIdServicio = new javax.swing.JLabel();
        txtIdServicio = new javax.swing.JTextField();
        cboNumComensales = new javax.swing.JComboBox<>();
        lblNumComensales = new javax.swing.JLabel();
        lblComentarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        btnAsignar = new javax.swing.JButton();
        lblMesa = new javax.swing.JLabel();
        lblTurno = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        txtMesa = new javax.swing.JTextField();
        txtTurno = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCamareros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("ASIGNAR CAMARERO");

        lblIdServicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIdServicio.setText("SERVICIO:");

        txtIdServicio.setEditable(false);

        cboNumComensales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- NUM COMENSALES --", "2", "4", "6" }));

        lblNumComensales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblNumComensales.setText("NÚMERO COMENSALES:");

        lblComentarios.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblComentarios.setText("COMENTARIOS:");

        txtComentarios.setColumns(20);
        txtComentarios.setRows(5);
        jScrollPane1.setViewportView(txtComentarios);

        btnAsignar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAsignar.setText("CONFIRMAR");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        lblMesa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMesa.setText("MESA:");

        lblTurno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTurno.setText("TURNO:");

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFecha.setText("FECHA:");

        txtMesa.setEditable(false);

        txtTurno.setEditable(false);

        txtFecha.setEditable(false);

        tableCamareros.setModel(modelo);
        jScrollPane2.setViewportView(tableCamareros);

        javax.swing.GroupLayout panelReservaMesasLayout = new javax.swing.GroupLayout(panelReservaMesas);
        panelReservaMesas.setLayout(panelReservaMesasLayout);
        panelReservaMesasLayout.setHorizontalGroup(
            panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservaMesasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(379, 379, 379))
            .addGroup(panelReservaMesasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelReservaMesasLayout.createSequentialGroup()
                        .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelReservaMesasLayout.createSequentialGroup()
                                .addComponent(lblIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIdServicio))
                            .addGroup(panelReservaMesasLayout.createSequentialGroup()
                                .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTurno)
                                    .addComponent(lblFecha)
                                    .addComponent(lblMesa)
                                    .addComponent(lblNumComensales))
                                .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panelReservaMesasLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtFecha)
                                                .addComponent(cboNumComensales, javax.swing.GroupLayout.Alignment.TRAILING, 0, 329, Short.MAX_VALUE))
                                            .addComponent(txtTurno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservaMesasLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(105, 105, 105)
                        .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComentarios, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAsignar)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelReservaMesasLayout.setVerticalGroup(
            panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservaMesasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReservaMesasLayout.createSequentialGroup()
                        .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdServicio)
                            .addComponent(txtIdServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblComentarios))
                        .addGap(18, 18, 18)
                        .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMesa)
                            .addComponent(txtMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTurno)
                            .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelReservaMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboNumComensales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumComensales)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnAsignar)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReservaMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReservaMesas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        int filaSeleccionada = tableCamareros.getSelectedRow();
        if (filaSeleccionada >= 0) {
            boolean exito = GestorServicio.asignarCamareroAServicio(Integer.parseInt(txtIdServicio.getText()), cboNumComensales.getSelectedItem().toString(), txtComentarios.getText(), Integer.parseInt(tableCamareros.getValueAt(filaSeleccionada, 0).toString()));
            if (exito) {
                this.setVisible(false);
                formGestion.setVisible(true);
                formGestion.cargarDatos();
                cerrar();
            } else {
                JOptionPane.showMessageDialog(null, "SE HA PRODUCIDO UN ERROR AL ASIGNAR EL CAMARERO", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UN CAMARERO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_Asignar_Camarero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_Asignar_Camarero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_Asignar_Camarero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_Asignar_Camarero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU_Asignar_Camarero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JComboBox<String> cboNumComensales;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIdServicio;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblNumComensales;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JPanel panelReservaMesas;
    private javax.swing.JTable tableCamareros;
    private javax.swing.JTextArea txtComentarios;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIdServicio;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
