/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.table.TableColumn;


public class IU_Anotar_Comanda extends javax.swing.JFrame {

    private final WindowListener exitListener;
    private IU_Gestion_Comandas formComandas;
    private ModeloTabla modelo;
    
    /**
     * Creates new form IU_Anotar_Comanda
     */
    public IU_Anotar_Comanda() {
        this.exitListener = new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                formComandas.setVisible(true);
                cerrar();
            }
        };
        
        //Establecemos el modelo de tabla
        modelo = new ModeloTabla();
        
        initComponents();
        
        this.setTitle("ANOTAR COMANDA");
        this.setLocationRelativeTo(null); 
        this.addWindowListener(exitListener);
        
        //Ajustes de la tabla
        tablaLineas.getTableHeader().setReorderingAllowed(false);
        cargarTabla();
    }
    
    private void cargarTabla() {
        String nombreColumnas [] = {"ID_PRODUCTO", "DESCRIPCION", "TIPO PRODUCTO", "PRECIO", "CANTIDAD"};
        
        for (String nombreColumna : nombreColumnas) {
            modelo.addColumn(nombreColumna);
        }
        
        TableColumn id = tablaLineas.getColumn("ID_PRODUCTO");
        id.setMinWidth(80);
        
        TableColumn descripcion = tablaLineas.getColumn("DESCRIPCION");
        descripcion.setMinWidth(80);
        
        TableColumn tipo = tablaLineas.getColumn("TIPO PRODUCTO");
        tipo.setMinWidth(80);
        
        TableColumn precio = tablaLineas.getColumn("PRECIO");
        precio.setMinWidth(80);
        
        TableColumn cantidad = tablaLineas.getColumn("CANTIDAD");
        cantidad.setMinWidth(80);
    }
    
    public void setFormGestionComandas (IU_Gestion_Comandas formComandas) {
        this.formComandas = formComandas;
    }
    
    public void setDatosComanda (String idServicio, String turno, String mesa, String fecha, String comensales) {
        txtServicio.setText(idServicio);
        txtTurno.setText(turno);
        txtMesa.setText(mesa);
        txtFecha.setText(fecha);
        txtComensales.setText(comensales);
        txtTotal.setText("0");
    }
    
    private void cerrar() {
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAnotar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLineas = new javax.swing.JTable();
        btnAnotarComanda = new javax.swing.JButton();
        lblTituloComanda = new javax.swing.JLabel();
        lblServicio = new javax.swing.JLabel();
        lblMesa = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        txtMesa = new javax.swing.JTextField();
        txtTurno = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        txtComensales = new javax.swing.JTextField();
        btnAñadirLinea = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTurno = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblComensales = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblUnidadMonetaria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        tablaLineas.setModel(modelo);
        jScrollPane1.setViewportView(tablaLineas);

        btnAnotarComanda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAnotarComanda.setText("CONFIRMAR COMANDA");

        lblTituloComanda.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTituloComanda.setText("COMANDA");

        lblServicio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblServicio.setText("SERVICIO:");

        lblMesa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMesa.setText("MESA:");

        txtServicio.setEditable(false);

        txtMesa.setEditable(false);

        txtTurno.setEditable(false);

        txtFecha.setEditable(false);

        txtComensales.setEditable(false);

        btnAñadirLinea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAñadirLinea.setText("AÑADIR");
        btnAñadirLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirLineaActionPerformed(evt);
            }
        });

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModificar.setText("MODIFICAR");

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");

        lblTurno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTurno.setText("TURNO:");

        lblFecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblFecha.setText("FECHA:");

        lblComensales.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblComensales.setText("NÚMERO COMENSALES:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setText("TOTAL COMANDA:");

        txtTotal.setEditable(false);

        lblUnidadMonetaria.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUnidadMonetaria.setText("€");

        javax.swing.GroupLayout panelAnotarLayout = new javax.swing.GroupLayout(panelAnotar);
        panelAnotar.setLayout(panelAnotarLayout);
        panelAnotarLayout.setHorizontalGroup(
            panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAnotarLayout.createSequentialGroup()
                .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAnotarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTurno))
                    .addGroup(panelAnotarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1)
                            .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAnotarLayout.createSequentialGroup()
                                    .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelAnotarLayout.createSequentialGroup()
                                            .addComponent(btnAñadirLinea)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnModificar)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnEliminar))
                                        .addGroup(panelAnotarLayout.createSequentialGroup()
                                            .addComponent(lblServicio)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnAnotarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelAnotarLayout.createSequentialGroup()
                                            .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(panelAnotarLayout.createSequentialGroup()
                                                    .addComponent(lblFecha)
                                                    .addGap(50, 50, 50)
                                                    .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtTurno)
                                                        .addComponent(txtFecha)
                                                        .addGroup(panelAnotarLayout.createSequentialGroup()
                                                            .addComponent(txtMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(0, 0, Short.MAX_VALUE))))
                                                .addComponent(lblMesa))
                                            .addGap(137, 137, 137)
                                            .addComponent(lblTotal)))
                                    .addGap(69, 69, 69)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblUnidadMonetaria))
                                .addGroup(panelAnotarLayout.createSequentialGroup()
                                    .addGap(506, 506, 506)
                                    .addComponent(lblComensales)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtComensales, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panelAnotarLayout.createSequentialGroup()
                        .addGap(433, 433, 433)
                        .addComponent(lblTituloComanda)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAnotarLayout.setVerticalGroup(
            panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAnotarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTituloComanda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblServicio)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComensales)
                    .addComponent(txtComensales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMesa)
                    .addComponent(txtMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUnidadMonetaria))
                .addGap(18, 18, 18)
                .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTurno)
                    .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha))
                .addGap(42, 42, 42)
                .addGroup(panelAnotarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAñadirLinea)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnotarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAnotar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAnotar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAñadirLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirLineaActionPerformed
        this.setVisible(false);
        IU_Anotar_Linea_Comanda anotarLineaComanda = new IU_Anotar_Linea_Comanda();
        anotarLineaComanda.setFormAnotarComanda(this);
        anotarLineaComanda.setVisible(true);
    }//GEN-LAST:event_btnAñadirLineaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_Anotar_Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_Anotar_Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_Anotar_Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_Anotar_Comanda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU_Anotar_Comanda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnotarComanda;
    private javax.swing.JButton btnAñadirLinea;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblComensales;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMesa;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblTituloComanda;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTurno;
    private javax.swing.JLabel lblUnidadMonetaria;
    private javax.swing.JPanel panelAnotar;
    private javax.swing.JTable tablaLineas;
    private javax.swing.JTextField txtComensales;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMesa;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
