/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.LineaComanda;
import Dominio.Producto;
import javax.swing.JOptionPane;


public class IU_Anotar_Linea_Comanda_Dialog extends javax.swing.JDialog {

    private IU_Anotar_Comanda_Dialog formAnotarComanda;
    private char modo;
    private int numLinea;
    
    /**
     * Creates new form IU_Anotar_Linea_Comanda_Dialog
     */
    public IU_Anotar_Linea_Comanda_Dialog(java.awt.Frame parent, boolean modal, char modo) {
        super(parent, modal);
        
        this.modo = modo;
        
        initComponents();
           
        if (this.modo == 'M') {
            btnSeleccionarProducto.setEnabled(false);
        }
        
        this.setTitle("ANOTAR LINEA COMANDA");
        this.setLocationRelativeTo(parent); 
    }

    public void setInformacion (Producto p) {
        txtIdProducto.setText(String.valueOf(p.getIdProducto()));
        txtDescripcion.setText(p.getDescripcionProducto());
        txtTipoProducto.setText(p.getTipoProducto());
        txtPrecio.setText(String.valueOf(p.getPrecio()));
    }
    
    public void setNumeroLinea (int numLinea) {
        this.numLinea = numLinea;
    }
    
    public void setInformacion (Producto p, int cantidad) {
        txtIdProducto.setText(String.valueOf(p.getIdProducto()));
        txtDescripcion.setText(p.getDescripcionProducto());
        txtTipoProducto.setText(p.getTipoProducto());
        txtPrecio.setText(String.valueOf(p.getPrecio()));
        txtCantidad.setValue(cantidad);
    }
    
    
    public void setFormAnotarComanda (IU_Anotar_Comanda_Dialog formAnotarComanda) {
        this.formAnotarComanda = formAnotarComanda;
    }
    
    private void cerrar() {
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblIdProducto = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblTipoProducto = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtIdProducto = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtTipoProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnConfirmarLinea = new javax.swing.JButton();
        btnSeleccionarProducto = new javax.swing.JButton();
        txtCantidad = new com.toedter.components.JSpinField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("LINEA COMANDA");

        lblIdProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblIdProducto.setText("ID PRODUCTO:");

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDescripcion.setText("DESCRIPCION:");

        lblTipoProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTipoProducto.setText("TIPO PRODUCTO:");

        lblPrecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPrecio.setText("PRECIO:");

        lblCantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCantidad.setText("CANTIDAD:");

        txtIdProducto.setEditable(false);

        txtDescripcion.setEditable(false);

        txtTipoProducto.setEditable(false);

        txtPrecio.setEditable(false);

        btnConfirmarLinea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConfirmarLinea.setText("CONFIRMAR LINEA");
        btnConfirmarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarLineaActionPerformed(evt);
            }
        });

        btnSeleccionarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSeleccionarProducto.setText("SELECCIONAR");
        btnSeleccionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarProductoActionPerformed(evt);
            }
        });

        txtCantidad.setMaximum(6);
        txtCantidad.setMinimum(0);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConfirmarLinea, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCantidad)
                                    .addComponent(lblPrecio)
                                    .addComponent(lblTipoProducto)
                                    .addComponent(lblDescripcion)
                                    .addComponent(lblIdProducto))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtIdProducto)
                                    .addComponent(txtPrecio)
                                    .addComponent(txtTipoProducto)
                                    .addComponent(txtDescripcion)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE))
                                .addGap(31, 31, 31)
                                .addComponent(btnSeleccionarProducto))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(lblTitulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdProducto)
                    .addComponent(btnSeleccionarProducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripcion))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTipoProducto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrecio, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnConfirmarLinea)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarLineaActionPerformed
        int cantidad;
        if (!txtIdProducto.getText().equals("")) {
            cantidad = comprobarValue();
            if (cantidad > 0) {
                this.setVisible(false);

                if (this.modo == 'A') {
                    formAnotarComanda.aniadirLineaComanda(new LineaComanda(new Producto(Integer.parseInt(txtIdProducto.getText()), txtDescripcion.getText(), txtTipoProducto.getText(), Float.parseFloat(txtPrecio.getText())), cantidad, Float.parseFloat(txtPrecio.getText())));
                } else {
                    formAnotarComanda.modificarLineaComanda(numLinea, cantidad);
                }

                cerrar();
            } else {
                JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UNA CANTIDAD VALIDA", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UN PRODUCTO", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnConfirmarLineaActionPerformed

    private int comprobarValue () {
        int cantidad = 0;
        try {
            cantidad = txtCantidad.getValue();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UNA CANTIDAD VALIDA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
        return cantidad;
    }
    
    private void btnSeleccionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarProductoActionPerformed
        IU_Productos_Dialog productos = new IU_Productos_Dialog(null, true);
        productos.setFormAnotarLineaComanda(this);
        productos.setVisible(true);
    }//GEN-LAST:event_btnSeleccionarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_Anotar_Linea_Comanda_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_Anotar_Linea_Comanda_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_Anotar_Linea_Comanda_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_Anotar_Linea_Comanda_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IU_Anotar_Linea_Comanda_Dialog dialog = new IU_Anotar_Linea_Comanda_Dialog(new javax.swing.JFrame(), true, 'A');
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarLinea;
    private javax.swing.JButton btnSeleccionarProducto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipoProducto;
    private javax.swing.JLabel lblTitulo;
    private com.toedter.components.JSpinField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTipoProducto;
    // End of variables declaration//GEN-END:variables
}
