/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Empleado;
import Dominio.GestorComandas;
import Dominio.Restaurante;
import Dominio.Servicio;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.TableColumn;

/**
 *
 * @author pikac
 */
public class IU_Gestion_Comandas extends javax.swing.JFrame {

    public static Empleado sesionEmpleado;
    private ModeloTabla modelo;
    
    /**
     * Creates new form IU_Gestion_Comandas
     */
    public IU_Gestion_Comandas() {
        //Se establece el empleado hasta que tengamos un sistema de login
        sesionEmpleado = new Empleado (1, "11111111A", "CAMARERO", "1", 926123456, Empleado.Rol.CAMARERO, new Restaurante(1));
        
        //Establecemos el modelo de tabla
        modelo = new ModeloTabla();
        
        initComponents();
        
        //Se ponen las propiedades para la ventana
        this.setTitle("GESTIÓN DE COMANDAS");
        this.setLocationRelativeTo(null);
        
        //Ajustes de la tabla
        tablaServicios.getTableHeader().setReorderingAllowed(false);
        cargarTabla(); cargarDatos(); 
    }
    
    private void cargarTabla() {
        String nombreColumnas [] = {"ID_SERVICIO", "FECHA", "TURNO", "MESA", "ESTADO", "NUM_COMENSALES"};
        
        for (String nombreColumna : nombreColumnas) {
            modelo.addColumn(nombreColumna);
        }
        
        TableColumn id = tablaServicios.getColumn("ID_SERVICIO");
        id.setMinWidth(80);
        
        TableColumn fecha = tablaServicios.getColumn("FECHA");
        fecha.setMinWidth(80);
        
        TableColumn turno = tablaServicios.getColumn("TURNO");
        turno.setMinWidth(80);
        
        TableColumn mesa = tablaServicios.getColumn("MESA");
        mesa.setMinWidth(80);
        
        TableColumn estado = tablaServicios.getColumn("ESTADO");
        estado.setMinWidth(80);
        
        TableColumn comensales = tablaServicios.getColumn("NUM_COMENSALES");
        comensales.setMinWidth(80);
    }
    
    public void cargarDatos() {
        DateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        
        ArrayList<Servicio> lista = GestorComandas.buscarListaServicios(sesionEmpleado);
        
        Object[] obj = new Object[6];
        for (int i = 0; i < lista.size(); i++) {
            Servicio s = lista.get(i);
            
            obj[0] = s.getIdServicio();
            obj[1] = formatter.format(s.getFecha());
            obj[2] = s.getnTurno();
            obj[3] = s.getnMesa();
            obj[4] = s.getEstado().toString();
            obj[5] = s.getNum_comensales();
            
            modelo.addRow(obj);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelReservas = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnAnotarComanda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaServicios = new javax.swing.JTable();
        btnBuscarServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("GESTIÓN DE RESERVAS");

        btnAnotarComanda.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAnotarComanda.setText("ANOTAR COMANDA");
        btnAnotarComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnotarComandaActionPerformed(evt);
            }
        });

        tablaServicios.setModel(modelo);
        jScrollPane1.setViewportView(tablaServicios);

        btnBuscarServicio.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnBuscarServicio.setText("BUSCAR SERVICIOS");
        btnBuscarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReservasLayout = new javax.swing.GroupLayout(panelReservas);
        panelReservas.setLayout(panelReservasLayout);
        panelReservasLayout.setHorizontalGroup(
            panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservasLayout.createSequentialGroup()
                .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReservasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelReservasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAnotarComanda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarServicio)))
                .addContainerGap())
            .addGroup(panelReservasLayout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(lblTitulo)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        panelReservasLayout.setVerticalGroup(
            panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReservasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(panelReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnotarComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 25, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelReservas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnotarComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnotarComandaActionPerformed
        int filaSeleccionada = tablaServicios.getSelectedRow();
        if (filaSeleccionada >= 0) {
            if (tablaServicios.getValueAt(filaSeleccionada, 4).equals("LIBRE")) {
//                this.setVisible(false);
//                IU_Reservar_Mesa reservarMesa = new IU_Reservar_Mesa();
//                reservarMesa.setFormGestionReservas(this);
//                reservarMesa.setVisible(true);
//                reservarMesa.setDatosServicio(tablaServicios.getValueAt(filaSeleccionada, 0).toString(), tablaServicios.getValueAt(filaSeleccionada, 2).toString(), tablaServicios.getValueAt(filaSeleccionada, 3).toString(), tablaServicios.getValueAt(filaSeleccionada, 1).toString());
            } else {
                //JOptionPane.showMessageDialog(null, "EL ESTADO DEL SERVICIO DEBE SER LIBRE PARA PODER SER RESERVADO", "NO SE PUEDE RESERVAR ESA MESA", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            //JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UN SERVICIO", "NO SE PUEDE RESERVAR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAnotarComandaActionPerformed

    private void btnBuscarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarServicioActionPerformed
        cargarDatos();
    }//GEN-LAST:event_btnBuscarServicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_Gestion_Comandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_Gestion_Comandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_Gestion_Comandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_Gestion_Comandas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU_Gestion_Comandas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnotarComanda;
    private javax.swing.JButton btnBuscarServicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelReservas;
    private javax.swing.JTable tablaServicios;
    // End of variables declaration//GEN-END:variables
}
