/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Empleado;
import Dominio.GestorLineasComanda;
import Dominio.LineaComanda;
import Dominio.Restaurante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;

/**
 *
 * @author pikac
 */
public class IU_Lineas_Empleado extends javax.swing.JFrame {

    public static Empleado sesionEmpleado;
    private static Empleado[] empleadosPrueba;
    private ModeloTabla modelo;
    
    /**
     * Creates new form IU_Lineas_Empleado
     */
    public IU_Lineas_Empleado() {
        empleadosPrueba = new Empleado[3];
        empleadosPrueba[0] = new Empleado (1, "11111111A", "CAMARERO", "1", 926123456, Empleado.Rol.CAMARERO, new Restaurante(1));
        empleadosPrueba[1] = new Empleado (4, "44444444D", "CAMARERO", "DE BARRA", 926123459, Empleado.Rol.CAMARERO_BARRA, new Restaurante(1));
        empleadosPrueba[2] = new Empleado (5, "55555555E", "COCINERO", "1", 926123450, Empleado.Rol.COCINERO, new Restaurante(1));
        
        
        //Se establece el empleado hasta que tengamos un sistema de login
        sesionEmpleado = empleadosPrueba[0];
        
        //Establecemos el modelo de tabla
        modelo = new ModeloTabla();
        
        initComponents();
        
        //Se ponen las propiedades para la ventana
        this.setTitle("GESTIÓN DE PRODUCTOS PENDIENTES");
        this.setLocationRelativeTo(null);
        
        //Ajustes de la tabla
        tablaLineasPendientes.getTableHeader().setReorderingAllowed(false);
        cargarTabla(); cargarDatos();
    }
    
    private void cargarTabla() {
        String nombreColumnas [] = {"ID_COMANDA", "ID_LINEA_COMANDA", "ID_PRODUCTO", "DESCRIPCION_PRODUCTO", "TIPO_PRODUCTO", "CANTIDAD", "NOMBRE_MESA"};
        
        for (String nombreColumna : nombreColumnas) {
            modelo.addColumn(nombreColumna);
        }
        
        TableColumn idComanda = tablaLineasPendientes.getColumn("ID_COMANDA");
        idComanda.setMinWidth(20);
        
        TableColumn idLineaComanda = tablaLineasPendientes.getColumn("ID_LINEA_COMANDA");
        idLineaComanda.setMinWidth(20);
        
        TableColumn idProducto = tablaLineasPendientes.getColumn("ID_PRODUCTO");
        idProducto.setMinWidth(20);
        
        TableColumn descripcionProducto = tablaLineasPendientes.getColumn("DESCRIPCION_PRODUCTO");
        descripcionProducto.setMinWidth(80);
        
        TableColumn tipoProducto = tablaLineasPendientes.getColumn("TIPO_PRODUCTO");
        tipoProducto.setMinWidth(80);
        
        TableColumn cantidad = tablaLineasPendientes.getColumn("CANTIDAD");
        cantidad.setMinWidth(20);
        
        TableColumn nombreMesa = tablaLineasPendientes.getColumn("NOMBRE_MESA");
        nombreMesa.setMinWidth(80);
    }
    
    public void cargarDatos() {
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        
        ArrayList<LineaComanda> lista = GestorLineasComanda.buscarLineasComandaPendientes(sesionEmpleado.getIdEmpleado(), sesionEmpleado.getTipoEmpleado().toString());
        
        Object[] obj = new Object[7];
        for (int i = 0; i < lista.size(); i++) {
            LineaComanda l = lista.get(i);
            
            obj[0] = l.getComanda().getIdComanda();
            obj[1] = l.getIdLineaComanda();
            obj[2] = l.getnLinea().getIdProducto();
            obj[3] = l.getnLinea().getDescripcionProducto();
            obj[4] = l.getnLinea().getTipoProducto();
            obj[5] = l.getCantidad();
            obj[6] = l.getComanda().getServicio().getnMesa().getNombreMesa();
            
            modelo.addRow(obj);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLineasPendientes = new javax.swing.JTable();
        btnServir = new javax.swing.JButton();
        btnVerLineas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("PRODUCTOS POR SERVIR");

        tablaLineasPendientes.setModel(modelo);
        jScrollPane1.setViewportView(tablaLineasPendientes);

        btnServir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnServir.setText("CONFIRMAR LINEA");
        btnServir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnServirActionPerformed(evt);
            }
        });

        btnVerLineas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnVerLineas.setText("VER PRODUCTOS PENDIENTES");
        btnVerLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerLineasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(lblTitulo)
                .addContainerGap(388, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnServir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerLineas)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnServir)
                    .addComponent(btnVerLineas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerLineasActionPerformed
        cargarDatos();
    }//GEN-LAST:event_btnVerLineasActionPerformed

    private void btnServirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServirActionPerformed
        int filaSeleccionada = tablaLineasPendientes.getSelectedRow();
        if (filaSeleccionada >= 0) {
            int input = JOptionPane.showConfirmDialog(this, "¿Quieres realizar dicha operación?", "Selecciona una opción...", JOptionPane.YES_NO_OPTION);
            if (input == 0) {
                if (GestorLineasComanda.actualizarLineaServida(Integer.parseInt(tablaLineasPendientes.getValueAt(filaSeleccionada, 1).toString()))) {
                    GestorLineasComanda.actualizarEstadoServicio(Integer.parseInt(tablaLineasPendientes.getValueAt(filaSeleccionada, 0).toString()));
                    cargarDatos();
                } else {
                    JOptionPane.showMessageDialog(this, "NO SE PUEDE CAMBIAR EL ESTADO DE LA LINEA", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }   
        } else {
            JOptionPane.showMessageDialog(this, "SELECCIONA UNA LINEA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnServirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_Lineas_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_Lineas_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_Lineas_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_Lineas_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU_Lineas_Empleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnServir;
    private javax.swing.JButton btnVerLineas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaLineasPendientes;
    // End of variables declaration//GEN-END:variables
}
