/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Empleado;


public class IU_Principal extends javax.swing.JFrame {

    public static Empleado sesionEmpleado;
    
    /**
     * Creates new form IU_Principal
     */
    public IU_Principal() {
        initComponents();
        
        this.setTitle("GESTIÓN DE RESTAURANTES");
        
        switch (sesionEmpleado.getTipoEmpleado().toString()) {
            case "JEFE_DE_SALA":
                gestionReservarMenuItem.setEnabled(true);
                comandasPendientes.setEnabled(false);
                confirmarLineasServidas.setEnabled(false);
                almacenMenuItem.setEnabled(false);
                pagoLiberacionMenu.setEnabled(false);
                estadisticas.setEnabled(false);
                break;
            case "CAMARERO":
                gestionReservarMenuItem.setEnabled(false);
                comandasPendientes.setEnabled(true);
                confirmarLineasServidas.setEnabled(true);
                almacenMenuItem.setEnabled(false);
                pagoLiberacionMenu.setEnabled(true);
                estadisticas.setEnabled(false);
                break;
            case "CAMARERO_BARRA":
                gestionReservarMenuItem.setEnabled(false);
                comandasPendientes.setEnabled(false);
                confirmarLineasServidas.setEnabled(true);
                almacenMenuItem.setEnabled(false);
                pagoLiberacionMenu.setEnabled(false);
                estadisticas.setEnabled(false);
                break;
            case "COCINERO":
                gestionReservarMenuItem.setEnabled(false);
                comandasPendientes.setEnabled(false);
                confirmarLineasServidas.setEnabled(true);
                almacenMenuItem.setEnabled(false);
                pagoLiberacionMenu.setEnabled(false);
                estadisticas.setEnabled(false);
                break;
            case "ALMACEN":
                gestionReservarMenuItem.setEnabled(true);
                comandasPendientes.setEnabled(false);
                confirmarLineasServidas.setEnabled(false);
                almacenMenuItem.setEnabled(true);
                pagoLiberacionMenu.setEnabled(false);
                estadisticas.setEnabled(false);
                break;
            case "DIRECTIVO":
                gestionReservarMenuItem.setEnabled(false);
                comandasPendientes.setEnabled(false);
                confirmarLineasServidas.setEnabled(false);
                almacenMenuItem.setEnabled(false);
                pagoLiberacionMenu.setEnabled(false);
                estadisticas.setEnabled(true);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        reservaMenu = new javax.swing.JMenu();
        gestionReservarMenuItem = new javax.swing.JMenuItem();
        pedidosComandasMenu = new javax.swing.JMenu();
        comandasPendientes = new javax.swing.JMenuItem();
        confirmarLineasServidas = new javax.swing.JMenuItem();
        almacenMenu = new javax.swing.JMenu();
        almacenMenuItem = new javax.swing.JMenuItem();
        pagoLiberacionMenu = new javax.swing.JMenu();
        pagoLiberacion = new javax.swing.JMenuItem();
        estadisticasMenu = new javax.swing.JMenu();
        estadisticas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        reservaMenu.setMnemonic('f');
        reservaMenu.setText("Reserva mesas");

        gestionReservarMenuItem.setMnemonic('o');
        gestionReservarMenuItem.setText("Abrir gestion reservas");
        gestionReservarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionReservarMenuItemActionPerformed(evt);
            }
        });
        reservaMenu.add(gestionReservarMenuItem);

        menuBar.add(reservaMenu);

        pedidosComandasMenu.setText("Pedidos comandas");

        comandasPendientes.setText("Gestionar comandas pendientes");
        comandasPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comandasPendientesActionPerformed(evt);
            }
        });
        pedidosComandasMenu.add(comandasPendientes);

        confirmarLineasServidas.setText("Confirmar líneas servidas");
        confirmarLineasServidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarLineasServidasActionPerformed(evt);
            }
        });
        pedidosComandasMenu.add(confirmarLineasServidas);

        menuBar.add(pedidosComandasMenu);

        almacenMenu.setText("Almacén");

        almacenMenuItem.setText("Mostrar almacén");
        almacenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almacenMenuItemActionPerformed(evt);
            }
        });
        almacenMenu.add(almacenMenuItem);

        menuBar.add(almacenMenu);

        pagoLiberacionMenu.setText("Pago y liberación de mesas");

        pagoLiberacion.setText("Mostrar pago y liberación de mesas");
        pagoLiberacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoLiberacionActionPerformed(evt);
            }
        });
        pagoLiberacionMenu.add(pagoLiberacion);

        menuBar.add(pagoLiberacionMenu);

        estadisticasMenu.setText("Estadísticas");

        estadisticas.setText("Mostrar estadísticas");
        estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadisticasActionPerformed(evt);
            }
        });
        estadisticasMenu.add(estadisticas);

        menuBar.add(estadisticasMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionReservarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionReservarMenuItemActionPerformed
        desktopPane.removeAll();
        desktopPane.updateUI();
        IU_Gestion_Reservas_Internal.sesionEmpleado = sesionEmpleado;
        IU_Gestion_Reservas_Internal formGestionReservas = new IU_Gestion_Reservas_Internal ();
        desktopPane.add(formGestionReservas);
        formGestionReservas.show();
        formGestionReservas.setClosable(true);
    }//GEN-LAST:event_gestionReservarMenuItemActionPerformed

    private void comandasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comandasPendientesActionPerformed
        desktopPane.removeAll();
        desktopPane.updateUI();
        IU_Gestion_Comandas_Internal.sesionEmpleado = sesionEmpleado;
        IU_Gestion_Comandas_Internal formGestionComandas = new IU_Gestion_Comandas_Internal ();
        desktopPane.add(formGestionComandas);
        formGestionComandas.show();
        formGestionComandas.setClosable(true);
    }//GEN-LAST:event_comandasPendientesActionPerformed

    private void confirmarLineasServidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarLineasServidasActionPerformed
        desktopPane.removeAll();
        desktopPane.updateUI();
        IU_Lineas_Empleado_Internal.sesionEmpleado = sesionEmpleado;
        IU_Lineas_Empleado_Internal formLineasEmpleado = new IU_Lineas_Empleado_Internal ();
        desktopPane.add(formLineasEmpleado);
        formLineasEmpleado.show();
        formLineasEmpleado.setClosable(true);
    }//GEN-LAST:event_confirmarLineasServidasActionPerformed

    private void almacenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almacenMenuItemActionPerformed
        desktopPane.removeAll();
        desktopPane.updateUI();
        IU_Platos_Restaurante_Internal.sesionEmpleado = sesionEmpleado;
        IU_Platos_Restaurante_Internal formPlatosRestaurante = new IU_Platos_Restaurante_Internal ();
        desktopPane.add(formPlatosRestaurante);
        formPlatosRestaurante.show();
        formPlatosRestaurante.setClosable(true);
    }//GEN-LAST:event_almacenMenuItemActionPerformed

    private void estadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadisticasActionPerformed
        desktopPane.removeAll();
        desktopPane.updateUI();
        IU_Estadisticas_Internal formEstadisticas = new IU_Estadisticas_Internal ();
        desktopPane.add(formEstadisticas);
        formEstadisticas.show();
        formEstadisticas.setClosable(true);
    }//GEN-LAST:event_estadisticasActionPerformed

    private void pagoLiberacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoLiberacionActionPerformed
        desktopPane.removeAll();
        desktopPane.updateUI();
        IU_Pago_Liberacion_Internal.sesionEmpleado = sesionEmpleado;
        IU_Pago_Liberacion_Internal formPagoLiberacion = new IU_Pago_Liberacion_Internal ();
        desktopPane.add(formPagoLiberacion);
        formPagoLiberacion.show();
        formPagoLiberacion.setClosable(true);
    }//GEN-LAST:event_pagoLiberacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IU_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IU_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu almacenMenu;
    private javax.swing.JMenuItem almacenMenuItem;
    private javax.swing.JMenuItem comandasPendientes;
    private javax.swing.JMenuItem confirmarLineasServidas;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem estadisticas;
    private javax.swing.JMenu estadisticasMenu;
    private javax.swing.JMenuItem gestionReservarMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pagoLiberacion;
    private javax.swing.JMenu pagoLiberacionMenu;
    private javax.swing.JMenu pedidosComandasMenu;
    private javax.swing.JMenu reservaMenu;
    // End of variables declaration//GEN-END:variables

}
