/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Dominio.Estadistica;
import Dominio.GestorEstadisticas;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;


public class IU_Estadisticas_Internal extends javax.swing.JInternalFrame {

    private ModeloTabla modelo;
    
    /**
     * Creates new form IU_Estadisticas_Internal
     */
    public IU_Estadisticas_Internal() {
        //Establecemos el modelo de tabla
        modelo = new ModeloTabla();
        
        initComponents();
        
        //Se ponen las propiedades para la ventana
        this.setTitle("ESTADÍSTICAS");
        
        //Ajustes de la tabla
        tablaEstadisticas.getTableHeader().setReorderingAllowed(false);
        cargarTabla(); //cargarDatos(); 
    }

    private void cargarTabla() {
        String nombreColumnas [] = {"NOMBRE", "TIEMPO_TOTAL"};
        
        for (String nombreColumna : nombreColumnas) {
            modelo.addColumn(nombreColumna);
        }
        
        TableColumn id = tablaEstadisticas.getColumn("NOMBRE");
        id.setMinWidth(80);
        
        TableColumn fecha = tablaEstadisticas.getColumn("TIEMPO_TOTAL");
        fecha.setMinWidth(80);
    }
    
    public void cargarDatos() {
        modelo.getDataVector().removeAllElements();
        modelo.fireTableDataChanged();
        
        ArrayList<Estadistica> lista = GestorEstadisticas.buscarEstadisticas(cboTipoTiempo.getSelectedIndex() + " " + cboTipoBusqueda.getSelectedIndex());
        
        Object[] obj = new Object[2];
        for (int i = 0; i < lista.size(); i++) {
            Estadistica e = lista.get(i);
            
            obj[0] = e.getNombreId();
            obj[1] = e.getTiempoTotal();
            
            modelo.addRow(obj);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cboTipoTiempo = new javax.swing.JComboBox<>();
        cboTipoBusqueda = new javax.swing.JComboBox<>();
        lblTitulo = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstadisticas = new javax.swing.JTable();

        cboTipoTiempo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboTipoTiempo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- TIPO INFORMACION --", "TIEMPO TOMA COMANDAS", "TIEMPO PREPARACION COMIDA", "TIEMPO ENTREGA NOTA", "TIEMPO PREPARACION MESA" }));

        cboTipoBusqueda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cboTipoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- TIPO BUSQUEDA --", "POR RESTAURANTE", "POR CIUDAD" }));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("ESTADISTICAS");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaEstadisticas.setModel(modelo);
        jScrollPane1.setViewportView(tablaEstadisticas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(308, 308, 308)
                                .addComponent(lblTitulo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cboTipoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(cboTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)))
                        .addComponent(btnBuscar)
                        .addGap(153, 153, 153)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboTipoTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboTipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (cboTipoBusqueda.getSelectedIndex() > 0) {
            if (cboTipoTiempo.getSelectedIndex() > 0) {
                cargarDatos();
            } else {
                JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UN TIPO DE INFORMACION", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "DEBES SELECCIONAR UN TIPO DE BUSQUEDA", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox<String> cboTipoBusqueda;
    private javax.swing.JComboBox<String> cboTipoTiempo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaEstadisticas;
    // End of variables declaration//GEN-END:variables
}
